def form_field(data):
    return {
            "name": data["company_name"],
            "title": data["company_name"],
            "company": data["company_name"],
            "business": data["company_name"],
            "url": data["website_url"],
            "website": data["website_url"],
            "site": data["website_url"],
            "email": data["email"],
            "phone": data["phone"],
            "contact": data["phone"],
            "description": data["business_description"],
            "about": data["business_description"],
            "category": data["business_category"],
            "keywords": ", ".join(data["keywords"]),
            "tags": ", ".join(data["keywords"]),
            "address": data["address"],
            "city": data["location"].get("city", ""),
            "town": data["location"].get("city", ""),
            "town/city": data["location"].get("city", ""),
            "city/town": data["location"].get("city", ""),
            "state": data["location"].get("state", ""),
            "province": data["location"].get("state", ""),
            "region": data["location"].get("state", ""),
            "country": data["location"].get("country", ""),
            "nation": data["location"].get("country", ""),
            "zip": data["location"].get("zip", ""),
            "postal": data["location"].get("zip", ""),
            "postcode": data["location"].get("zip", ""),
            "zipcode": data["location"].get("zip", ""),
            "facebook": data["social_media_links"].get("facebook", ""),
            "twitter": data["social_media_links"].get("twitter", ""),
            "linkedin": data["social_media_links"].get("linkedin", ""),
            "instagram": data["social_media_links"].get("instagram", ""),
            "founder": data["founder_name"],
            "owner": data["founder_name"],
        }